/**
 * Upstream records.js parsing — shared by the node sync pipeline
 * (scripts/lib/leaderboard.mjs, re-exports from here) and the browser-side
 * live leaderboard refresh (components/LeaderboardClient.jsx fetches
 * records.js straight from upstream gh-pages, anonymous + CORS-open, so the
 * page no longer waits for our hourly CI poll that GitHub mostly drops).
 * Pure JS, no node builtins.
 */

export const UPSTREAM_RECORDS_URL =
  'https://raw.githubusercontent.com/Yawn-Sean/Daily_CF_Problems/gh-pages/records.js';

// Decode the compact skipped_dates field, e.g. "y2024,m03,,01,,15,m04,,02"
// (year token, month token, then two-digit days; empty tokens separate groups).
export function decodeSkippedDates(field) {
  const out = [];
  let y = 0;
  let m = 0;
  for (let s of field.split(',')) {
    s = s.trim();
    if (!s) continue;
    if (s[0] === 'y') y = parseInt(s.slice(1), 10);
    else if (s[0] === 'm') m = parseInt(s.slice(1), 10);
    else {
      for (let i = 0; i + 2 <= s.length; i += 2) {
        const d = parseInt(s.slice(i, i + 2), 10);
        if (y && m && d) out.push(`${y}-${String(m).padStart(2, '0')}-${String(d).padStart(2, '0')}`);
      }
    }
  }
  return out;
}

// records.js is generated by the upstream .github/workflows/records.py:
//   current_date:<latest counted day>
//   skipped_dates:<compact field>
//   <user>:<score>,<days>/<score>,<days>/...   (run-length encoded, oldest first;
//                                               score = min(2, problems solved that day))
export function parseRecordsJs(text) {
  let currentDate = null;
  const skippedDates = [];
  const users = [];
  for (let line of text.split(/[\r\n]+/)) {
    line = line.trim();
    if (!line || line.startsWith('let records') || line === '`;') continue;
    const idx = line.indexOf(':');
    if (idx <= 0) continue;
    const key = line.slice(0, idx);
    const value = line.slice(idx + 1);
    if (key === 'current_date') {
      currentDate = value;
    } else if (key === 'skipped_dates') {
      skippedDates.push(...decodeSkippedDates(value));
    } else {
      const runs = value
        .split('/')
        .map((run) => run.split(',').map(Number))
        .filter((r) => r.length === 2 && r.every((n) => Number.isInteger(n) && n >= 0));
      if (key && runs.length) users.push({ user: key, runs });
    }
  }
  if (!currentDate || !users.length) throw new Error('records.js: missing current_date or users');
  return { currentDate, skippedDates, users };
}

// Content signature for "did the leaderboard actually change" checks —
// generatedAt-style timestamps must never count as a change.
export function recordsSignature({ currentDate, skippedDates, users }) {
  return JSON.stringify({ currentDate, skippedDates, users });
}
