/**
 * Upstream community leaderboard sync (records.js from Yawn-Sean/Daily_CF_Problems
 * gh-pages). Shared by:
 *   - scripts/update-data.mjs        (full sync, end of main())
 *   - scripts/sync-leaderboard.mjs   (lightweight CI path: only the leaderboard changed)
 *
 * records.js is regenerated by the upstream records workflow on gh-pages, which
 * updates INDEPENDENTLY of the daily_problems commits on main — a leaderboard
 * change alone never moves the main-branch SHA that CI gates on, so it needs its
 * own SHA marker (data/.leaderboard-sha) and its own sync path.
 *
 * Uses only node builtins: the CI leaderboard-only path runs before `npm ci`.
 */
import { readFile, writeFile } from 'node:fs/promises';

const UPSTREAM = 'Yawn-Sean/Daily_CF_Problems';
const LEADERBOARD_BRANCH = 'gh-pages';

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/** Fetch records.js text: raw.githubusercontent with a contents-API fallback
    (some networks can't reach raw but can reach api.github.com). */
export async function fetchRecordsText(token = '') {
  const path = 'records.js';
  let lastErr;
  for (let attempt = 1; attempt <= 2; attempt++) {
    try {
      const res = await fetch(`https://raw.githubusercontent.com/${UPSTREAM}/${LEADERBOARD_BRANCH}/${path}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return await res.text();
    } catch (e) {
      lastErr = e;
      if (attempt < 2) await sleep(2000);
    }
  }
  try {
    const headers = { Accept: 'application/vnd.github+json', 'User-Agent': 'ys_problem_web' };
    if (token) headers.Authorization = `Bearer ${token}`;
    const res = await fetch(`https://api.github.com/repos/${UPSTREAM}/contents/${path}?ref=${LEADERBOARD_BRANCH}`, { headers });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const json = await res.json();
    if (json?.content) return Buffer.from(json.content, 'base64').toString('utf8');
  } catch (e) {
    lastErr = e;
  }
  throw new Error(`fetch records.js: ${lastErr?.message || 'all attempts failed'}`);
}

// Decode the compact skipped_dates field, e.g. "y2024,m03,,01,,15,m04,,02"
// (year token, month token, then two-digit days; empty tokens separate groups).
export function decodeSkippedDates(field) {
  const out = [];
  let y = 0;
  let m = 0;
  for (let s of field.split(',')) {
    s = s.trim();
    if (!s) continue;
    if (s[0] === 'y') y = parseInt(s.slice(1), 10);
    else if (s[0] === 'm') m = parseInt(s.slice(1), 10);
    else {
      for (let i = 0; i + 2 <= s.length; i += 2) {
        const d = parseInt(s.slice(i, i + 2), 10);
        if (y && m && d) out.push(`${y}-${String(m).padStart(2, '0')}-${String(d).padStart(2, '0')}`);
      }
    }
  }
  return out;
}

// records.js is generated by the upstream .github/workflows/records.py:
//   current_date:<latest counted day>
//   skipped_dates:<compact field>
//   <user>:<score>,<days>/<score>,<days>/...   (run-length encoded, oldest first;
//                                               score = min(2, problems solved that day))
export function parseRecordsJs(text) {
  let currentDate = null;
  const skippedDates = [];
  const users = [];
  for (let line of text.split(/[\r\n]+/)) {
    line = line.trim();
    if (!line || line.startsWith('let records') || line === '`;') continue;
    const idx = line.indexOf(':');
    if (idx <= 0) continue;
    const key = line.slice(0, idx);
    const value = line.slice(idx + 1);
    if (key === 'current_date') {
      currentDate = value;
    } else if (key === 'skipped_dates') {
      skippedDates.push(...decodeSkippedDates(value));
    } else {
      const runs = value
        .split('/')
        .map((run) => run.split(',').map(Number))
        .filter((r) => r.length === 2 && r.every((n) => Number.isInteger(n) && n >= 0));
      if (key && runs.length) users.push({ user: key, runs });
    }
  }
  if (!currentDate || !users.length) throw new Error('records.js: missing current_date or users');
  return { currentDate, skippedDates, users };
}

/**
 * Sync data/leaderboard.json from upstream records.js. Writes ONLY when the
 * parsed content actually changed (generatedAt excluded from the comparison),
 * so an unchanged leaderboard never produces a timestamp-only commit.
 *
 * Prints a machine-readable `LEADERBOARD-SYNC {...}` line for save-ci-log to
 * parse into the run summary.
 *
 * Returns { changed, players, currentDate }.
 */
export async function syncLeaderboardFile(file, { token = '' } = {}) {
  const text = await fetchRecordsText(token);
  const parsed = parseRecordsJs(text);
  const next = {
    generatedAt: new Date().toISOString(),
    sourceRepo: UPSTREAM,
    sourceBranch: LEADERBOARD_BRANCH,
    ...parsed,
  };

  let changed = true;
  try {
    const prev = JSON.parse(await readFile(file, 'utf8'));
    const shape = (o) =>
      JSON.stringify({ currentDate: o.currentDate, skippedDates: o.skippedDates, users: o.users });
    changed = shape(prev) !== shape(next);
  } catch {
    // missing or unreadable previous file → write
  }

  if (changed) {
    await writeFile(file, JSON.stringify(next, null, 2) + '\n');
    console.log(`  ✓ ${parsed.users.length} players, data through ${parsed.currentDate}`);
  } else {
    // keep the existing generatedAt — rewrite only on real changes
    console.log(`  ✓ ${parsed.users.length} players, data through ${parsed.currentDate} (unchanged)`);
  }
  console.log(
    `LEADERBOARD-SYNC ${JSON.stringify({
      changed,
      players: parsed.users.length,
      currentDate: parsed.currentDate,
    })}`,
  );
  return { changed, players: parsed.users.length, currentDate: parsed.currentDate };
}
